# fastify-postgres.yaml

# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastify-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/data/fastify-postgres' # Use a persistent path on your node

---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastify-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastify-postgres
  template:
    metadata:
      labels:
        app: fastify-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: 'postgres'
            - name: POSTGRES_PASSWORD
              value: 'postgres'
            - name: POSTGRES_DB
              value: 'postgres'
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: '/var/lib/postgresql/data'
              name: postgres-storage
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: fastify-postgres-pvc

---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: fastify-postgres
spec:
  type: ClusterIP
  selector:
    app: fastify-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
